### ISSUE TITLE
OpenGL 12297 error

### ISSUE THREAD

**Issue by emepetres** [Inokenty90/vibedocker#1]
Hi, executing the demo I'm getting an OpenGL error (12297), any thoughts?

Demo log:

```
root@21202efea6af:/vibe/vibe# python3.7 demo.py --vid_file sample_video.mp4 --output_folder output/
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp/sample_video_mp4/%06d.png"
Images saved to "/tmp/sample_video_mp4"
Input video number of frames 300
Downloading files from https://raw.githubusercontent.com/mkocabas/yolov3-pytorch/master/yolov3/config/yolov3.cfg
--2021-02-05 13:49:28--  https://raw.githubusercontent.com/mkocabas/yolov3-pytorch/master/yolov3/config/yolov3.cfg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.132.133, 151.101.132.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.132.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8338 (8.1K) [text/plain]
Saving to: ‘/root/.torch/config/yolov3.cfg’

yolov3.cfg                    100%[=================================================>]   8.14K  --.-KB/s    in 0.002s

2021-02-05 13:49:28 (3.94 MB/s) - ‘/root/.torch/config/yolov3.cfg’ saved [8338/8338]

Running Multi-Person-Tracker
100%|███████████████████████████████████████████████████████████████████████████████████| 25/25 [00:22<00:00,  1.85it/s]
Finished. Detection + Tracking FPS 13.24
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/checkpoints/resnet50-19c8e357.pth
100%|██████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:28<00:00, 3.66MB/s]
WARNING: You are using a SMPL model, with only 10 shape coefficients.
=> loaded pretrained model from 'data/vibe_data/spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running VIBE on each tracklet...
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:11<00:00, 11.39s/it]
VIBE FPS: 26.33
Total time spent: 84.58 seconds (including model loading time).
Total FPS (including model loading time): 3.55.
Saving output results to "output/sample_video/vibe_output.pkl".
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "demo.py", line 403, in <module>
    main(args)
  File "demo.py", line 265, in main
    renderer = Renderer(resolution=(orig_width, orig_height), orig_img=True, wireframe=args.wireframe)
  File "/vibe/vibe/lib/utils/renderer.py", line 60, in __init__
    point_size=1.0
  File "/usr/local/lib/python3.7/dist-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/usr/local/lib/python3.7/dist-packages/pyrender/offscreen.py", line 134, in _create
    self._platform.init_context()
  File "/usr/local/lib/python3.7/dist-packages/pyrender/platforms/egl.py", line 188, in init_context
    EGL_NO_CONTEXT, context_attributes
  File "/usr/local/lib/python3.7/dist-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/usr/local/lib/python3.7/dist-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 12297,
        baseOperation = eglCreateContext,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fca25f49e60>,
                <OpenGL._opaque.EGLConfig_pointer object at 0x7fca25f49dd0>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fca2568d050>,
                <OpenGL.arrays.lists.c_int_Array_7 object at 0x7fca25f13b90>,
        ),
        result = <OpenGL._opaque.EGLContext_pointer object at 0x7fca25f453b0>
)
```

**Comment by Inokenty90** [comment]
Maybe this issue will help you
https://github.com/mmatl/pyrender/issues/86

**Comment by emepetres** [comment]
Thanks @Inokenty90 , I already knew about that issue. Applying the suggested fix returns a sligtly different error:

```
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glRenderbufferStorageMultisample,
        cArguments = (
                GL_RENDERBUFFER,
                4,
                GL_RGBA,
                1920,
                1080,
        )
)
```

Are you able to run this image on a headless container? My run command is `docker run -it --gpus all --ipc=host inokenty/vibe /bin/bash`

**Comment by Inokenty90** [comment]
> 
> 
> Thanks @Inokenty90 , I already knew about that issue. Applying the suggested fix returns a sligtly different error:
> 
> ```
> OpenGL.error.GLError: GLError(
>         err = 1282,
>         description = b'invalid operation',
>         baseOperation = glRenderbufferStorageMultisample,
>         cArguments = (
>                 GL_RENDERBUFFER,
>                 4,
>                 GL_RGBA,
>                 1920,
>                 1080,
>         )
> )
> ```
> 
> Are you able to run this image on a headless container? My run command is `docker run -it --gpus all --ipc=host inokenty/vibe /bin/bash`

Yes, if you don't use vibe visualise options, you can use on headless container.

**Comment by emepetres** [comment]
Thanks @Inokenty90 , you mean no render at all, even if I'm not actually visualizing anything during the demo?
